---
- name: Deploy VM with disk creation and virt-install
  hosts: rhel-kvm
  gather_facts: false

  vars_prompt:
    - name: vm_name
      prompt: "Enter VM name"
      private: no

    - name: disk_size
      prompt: "Enter disk size (e.g., 30G)"
      private: no

    - name: cpu_count
      prompt: "Enter number of CPUs (e.g., 2)"
      private: no

    - name: disk_dir
      prompt: "Enter disk image path (default: /var/lib/libvirt/images)"
      private: no
      default: "/var/lib/libvirt/images"

    - name: iso_path
      prompt: "Enter path to ISO file for installation"
      private: no
      default: "/var/lib/libvirt/images/alma9.iso"

    - name: net_name
      prompt: "Enter network name (default: default)"
      private: no
      default: "default"

  vars:
    disk_path: "{{ disk_dir }}/{{ vm_name }}.qcow2"

  tasks:

    - name: Validate VM name is not empty
      ansible.builtin.assert:
        that:
          - vm_name | length > 0
        fail_msg: "VM name cannot be empty."

    - name: Validate disk size is not empty
      ansible.builtin.assert:
        that:
          - disk_size | length > 0
        fail_msg: "Disk size cannot be empty."

    - name: Validate CPU count is positive integer
      ansible.builtin.assert:
        that:
          - cpu_count is regex('^[0-9]+$')
          - cpu_count | int > 0
        fail_msg: "CPU count must be a positive integer."

    - name: Check if disk directory exists
      ansible.builtin.stat:
        path: "{{ disk_dir }}"
      register: disk_dir_stat

    - name: Fail if disk directory does not exist
      ansible.builtin.fail:
        msg: "Directory {{ disk_dir }} does not exist."
      when: not disk_dir_stat.stat.exists or not disk_dir_stat.stat.isdir

    - name: Check if ISO file exists
      ansible.builtin.stat:
        path: "{{ iso_path }}"
      register: iso_stat

    - name: Fail if ISO file not found
      ansible.builtin.fail:
        msg: "ISO file not found at {{ iso_path }}"
      when: not iso_stat.stat.exists or iso_stat.stat.isdir

    - name: Check if disk image already exists
      ansible.builtin.stat:
        path: "{{ disk_path }}"
      register: disk_stat

    - name: Inform disk image exists
      ansible.builtin.debug:
        msg: "Disk image already exists at {{ disk_path }}"
      when: disk_stat.stat.exists

    - name: Create QCOW2 disk image if not exists
      ansible.builtin.command:
        cmd: qemu-img create -f qcow2 "{{ disk_path }}" "{{ disk_size }}"
      async: 60
      poll: 0
      register: qemu_img_job
      when:
        - not ansible_check_mode
        - not disk_stat.stat.exists

    - name: Wait for disk image creation to finish (poll every 3 seconds)
      async_status
