---
collections:
  - name: redhat.openshift_virtualization
  - name: redhat.openshift
  - name: vmware.vmware_rest
  - name: ansible.posix
  - name: infra.aap_utilities
  - name: kubernetes.core
  - name: community.crypto
  - name: community.general
  - name: community.vmware


  # AAP 2.5+
  - name: ansible.platform
  - name: ansible.controller
  - name: infra.aap_configuration
...

